site_name: "EcoMLOps"
site_description: AI scale up for net zero

repo_name: fuzzylabs/ecomlops
repo_url: https://github.com/fuzzylabs/ecomlops

docs_dir: website

nav:
  - Introduction: 'index.md'

copyright: Copyright &copy; <a href="https://fuzzylabs.ai">Fuzzy Labs Ltd</a>