site_name: AI scale up for net zero
site_description: AI scale up for net zero

repo_name: fuzzylabs/ecomlops
repo_url: https://github.com/fuzzylabs/ecomlops

docs_dir: website

nav:
  - Introduction: "index.md"

theme:
  name: material
  features:
    - navigation.top
  logo: img/logo.png
  favicon: img/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fuzzy-labs/
      name: Fuzzy Labs on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/fuzzylabsai/
      name: Fuzzy Labs on Twitter
    - icon: simple/notion
      link: https://fuzzylabs.notion.site/
      name: EcoMLOps on Notion

extra_css:
  - css/extra.css

copyright: Copyright &copy; <a href="https://fuzzylabs.ai">Fuzzy Labs Ltd</a>
