FROM nvcr.io/nvidia/pytorch:24.06-py3-igpu

# Create a user group
RUN groupadd --gid 1000 appuser \
    && useradd --uid 1000 --gid 1000 -ms /bin/bash appuser

USER appuser

WORKDIR /app

COPY --chown=appuser:appuser . ./

CMD ["/bin/bash", "./run_experiment.sh"]