[project]
name = "power-logging"
version = "0.1.0"
description = "Collect power usage data during inference cycles for ImageNet pretrained CNN models."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3<1.36",
    "dvc-s3>=3.2.0",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "torch==2.2.2",
    "ultralytics>=8.3.69",
]

[dependency-groups]
dev = [
    "numpy<2",
    "pillow>=11.1.0",
    "torch==2.2.2", # last version available on intel macs, should be enough for dev work
]
