data:
  data_dir: "training_data"
  test_models: ["lenet", "resnet18", "vgg16"]
  cross_validation: 10

mlflow:
  enable_tracking: True
  mlflow_experiment_name: "second-data-version-exp"
  dagshub_repo_owner: "fuzzylabs"
  dagshub_repo_name: "edge-vision-power-estimation"
