name: Bump raw data version
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - develop
    paths:
      - 'jetson/power_logging/raw_data/**.dvc'

jobs:
  bump_frontend_version:
    permissions:
      contents: write
    uses: ./.github/workflows/bump_version.yml
    with:
      tag_namespace: "raw"