name: Bump train data version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop
    paths:
      - 'model_training/training_data.dvc'

jobs:
  bump_frontend_version:
    permissions:
      contents: write
    uses: ./.github/workflows/bump_version.yml
    with:
      tag_namespace: "train"