name: Model training tests - CI
run-name: Run tests defined in `model_training`

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    branches:
      - main
      - develop
    paths: 'model_training/**/*.py'
  push:
    branches:
      - main
      - develop
    paths: 'model_training/**/*.py'

defaults:
  run:
    working-directory: model_training

jobs:
  model-training-tests:
    name: Run tests for `model_training`
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
  
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
