name: Model training tests - CI
run-name: Run tests defined in `model_training`

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  file-changes:
    name: Detect changes in Python files in the `model_training` folder
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get all changed Python files
        id: changed-python-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            model_training/**/*.py
      
      - name: Run step if any Python file(s) in `model_training` have changed
        if: ${{ steps.changed-python-files.outputs.any_changed == 'true' }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
        run: |
          echo "One or more Python files in the `model_training` folder have changed."
          echo "List of all changed files: $ALL_CHANGED_FILES"
